#!/usr/bin/env bash
# Setup script for Total Recall
# Creates directory structure and optionally installs watcher service
# Supports Linux (systemd + inotify) and macOS (launchd + fswatch)

set -euo pipefail

SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "$SKILL_DIR/scripts/_compat.sh"

WORKSPACE="${OPENCLAW_WORKSPACE:-$(cd "$SKILL_DIR/../.." && pwd)}"
MEMORY_DIR="${MEMORY_DIR:-$WORKSPACE/memory}"

echo "🧠 Total Recall — Setup"
echo "========================"
echo "Workspace: $WORKSPACE"
echo "Memory dir: $MEMORY_DIR"
echo "Skill dir: $SKILL_DIR"
echo "Platform: $(uname -s)"
echo ""

# --- Check dependencies ---
echo "Checking dependencies..."
MISSING=0
for bin in jq curl; do
  if ! command -v "$bin" &>/dev/null; then
    echo "❌ Missing: $bin"
    if $_IS_MACOS; then
      echo "   Install with: brew install $bin"
    else
      echo "   Install with: sudo apt install $bin  (Debian/Ubuntu)"
    fi
    MISSING=1
  fi
done
echo "Checking Python dependencies..."
if ! command -v python3 &>/dev/null; then
  echo "❌ Missing: python3 (3.9+ required)"
  if $_IS_MACOS; then
    echo "   Install with: brew install python3"
  else
    echo "   Install with: sudo apt install python3  (Debian/Ubuntu)"
  fi
  MISSING=1
elif ! python3 -c 'import yaml' &>/dev/null 2>&1; then
  echo "❌ Missing Python dependency: PyYAML"
  if $_IS_MACOS; then
    echo "   Install with: pip3 install PyYAML"
    echo "   Or:           brew install libyaml && pip3 install PyYAML"
  else
    echo "   Install with: sudo apt install python3-yaml  (Debian/Ubuntu)"
    echo "   Or:           python3 -m pip install PyYAML"
  fi
  MISSING=1
else
  echo "✅ python3 + PyYAML found"
fi
if [ "$MISSING" -eq 1 ]; then
  echo ""
  echo "Install missing dependencies and re-run setup."
  exit 1
fi
echo "✅ Core dependencies found (jq, curl)"

# Check file watcher availability
if $_IS_MACOS; then
  if has_fswatch; then
    echo "✅ fswatch found (reactive watcher available)"
  else
    echo "ℹ️  fswatch not found — reactive watcher won't be available"
    echo "   Install with: brew install fswatch"
    echo "   Cron-only mode works fine without it."
  fi
else
  if has_inotify; then
    echo "✅ inotifywait found (reactive watcher available)"
  else
    echo "ℹ️  inotifywait not found — reactive watcher won't be available"
    echo "   Install: sudo apt install inotify-tools (Debian/Ubuntu)"
    echo "   Or: sudo dnf install inotify-tools (Fedora/RHEL)"
  fi
fi

# --- Load .env and check API key ---
if [ -f "$WORKSPACE/.env" ]; then
  set -a
  if ! source "$WORKSPACE/.env" 2>/dev/null; then
    echo "⚠️  Failed to source $WORKSPACE/.env — check for shell syntax errors"
  fi
  set +a
fi

# Normalize provider vars (LLM_API_KEY preferred; OPENROUTER_API_KEY backward-compatible)
LLM_BASE_URL="${LLM_BASE_URL:-https://openrouter.ai/api/v1}"
LLM_API_KEY="${LLM_API_KEY:-${OPENROUTER_API_KEY:-}}"

if [ -z "${LLM_API_KEY:-}" ]; then
  echo ""
  echo "⚠️  No API key found. Add one of these to $WORKSPACE/.env:"
  echo "   LLM_API_KEY=<your-key>             (preferred)"
  echo "   OPENROUTER_API_KEY=sk-or-v1-xxxxx  (backward-compatible)"
  echo "   LLM scripts will fail until an API key is configured."
  echo ""
elif [[ "$LLM_BASE_URL" == "https://openrouter.ai/api/v1" && "$LLM_API_KEY" != sk-or-v1-* ]]; then
  echo ""
  echo "⚠️  LLM_BASE_URL points to OpenRouter but key does not start with 'sk-or-v1-'."
  echo "   Double-check your API key or set LLM_BASE_URL to your actual provider."
  echo ""
else
  echo "✅ API key found (format looks OK)"
fi
echo "   Run the observer once to verify your API key works."

# --- Create directories ---
echo ""
echo "Creating directory structure..."
mkdir -p "$MEMORY_DIR/observation-backups"
mkdir -p "$MEMORY_DIR/archive/observations"
mkdir -p "$MEMORY_DIR/dream-logs"
mkdir -p "$MEMORY_DIR/.dream-backups"
mkdir -p "$MEMORY_DIR/sensor-state"
mkdir -p "$WORKSPACE/logs"
mkdir -p "$WORKSPACE/research/dream-cycle-metrics/daily"
echo "✅ Directories created"

# --- Create initial observations file ---
if [ ! -f "$MEMORY_DIR/observations.md" ]; then
  cat > "$MEMORY_DIR/observations.md" << 'EOF'
# Observations Log

Auto-generated by Observer agent. Loaded at session startup for cross-session memory.

---

EOF
  echo "✅ Created observations.md"
else
  echo "ℹ️  observations.md already exists, keeping it"
fi

# --- Create default AIE config ---
mkdir -p "$WORKSPACE/config"
if [ ! -e "$WORKSPACE/config/aie.yaml" ]; then
  cp "$SKILL_DIR/config/aie.yaml" "$WORKSPACE/config/aie.yaml"
  echo "✅ Created config/aie.yaml from template"
else
  echo "ℹ️  config/aie.yaml already exists, keeping it"
fi

# --- Make scripts executable ---
chmod +x "$SKILL_DIR/scripts/"*.sh
echo "✅ Scripts made executable"

# --- Install watcher service ---
if $_IS_MACOS; then
  # macOS: install LaunchAgent with fswatch
  if has_fswatch; then
    echo ""
    echo "Installing reactive watcher LaunchAgent (macOS)..."
    LAUNCHD_DIR="$HOME/Library/LaunchAgents"
    PLIST_NAME="com.total-recall.watcher"
    PLIST_FILE="$LAUNCHD_DIR/${PLIST_NAME}.plist"
    mkdir -p "$LAUNCHD_DIR"

    cat > "$PLIST_FILE" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${PLIST_NAME}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${SKILL_DIR}/scripts/observer-watcher.sh</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>OPENCLAW_WORKSPACE</key>
    <string>${WORKSPACE}</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>StandardOutPath</key>
  <string>${WORKSPACE}/logs/observer-watcher.stdout.log</string>
  <key>StandardErrorPath</key>
  <string>${WORKSPACE}/logs/observer-watcher.stderr.log</string>
  <key>ThrottleInterval</key>
  <integer>30</integer>
</dict>
</plist>
EOF

    # Unload if already loaded, then load
    launchctl bootout "gui/$(id -u)/$PLIST_NAME" 2>/dev/null || true
    launchctl bootstrap "gui/$(id -u)" "$PLIST_FILE" 2>/dev/null || true
    echo "✅ Watcher LaunchAgent installed and loaded"
  else
    echo ""
    echo "ℹ️  Skipping reactive watcher (fswatch not found)"
    echo "   Install fswatch with: brew install fswatch"
    echo "   The cron-based observer (every 15 min) provides full coverage without it."
  fi
elif has_inotify && has_systemd_user; then
  # Linux: install systemd user service
  echo ""
  echo "Installing reactive watcher service..."
  SYSTEMD_DIR="$HOME/.config/systemd/user"
  mkdir -p "$SYSTEMD_DIR"

  cat > "$SYSTEMD_DIR/total-recall-watcher.service" << EOF
[Unit]
Description=Total Recall — Reactive Observer Watcher
After=default.target

[Service]
Type=simple
ExecStart=$SKILL_DIR/scripts/observer-watcher.sh
Restart=on-failure
RestartSec=30
Environment=OPENCLAW_WORKSPACE=$WORKSPACE

[Install]
WantedBy=default.target
EOF

  systemctl --user daemon-reload
  systemctl --user enable total-recall-watcher.service
  systemctl --user start total-recall-watcher.service 2>/dev/null || true
  echo "✅ Watcher service installed and started"
else
  echo ""
  echo "ℹ️  Skipping reactive watcher service"
  if $_IS_MACOS; then
    echo "   Install fswatch with: brew install fswatch"
  else
    echo "   Requires Linux + systemd + inotify-tools"
  fi
  echo "   The cron-based observer (every 15 min) provides full coverage without it."
fi

# --- Print next steps ---
echo ""
echo "================================================"
echo "🎉 Setup complete!"
echo "================================================"
echo ""
echo "Next steps — you need to configure these manually:"
echo ""
echo "1. ADD CRON JOBS (via OpenClaw cron or system crontab):"
echo ""
echo "   # Observer — every 15 minutes"
echo "   */15 * * * * OPENCLAW_WORKSPACE=$WORKSPACE bash $SKILL_DIR/scripts/observer-agent.sh >> $WORKSPACE/logs/observer.log 2>&1"
echo ""
echo "   # Reflector — hourly check"
echo "   0 * * * * OPENCLAW_WORKSPACE=$WORKSPACE bash $SKILL_DIR/scripts/reflector-agent.sh >> $WORKSPACE/logs/reflector.log 2>&1"
echo ""
echo "   # Dream Cycle — nightly (3am recommended; adjust to your timezone)"
echo "   # The dream cycle runs as a full agent turn — NOT as a direct bash call."
echo "   # dream-cycle.sh is a file operations helper called BY the agent, not the entry point."
echo "   #"
echo "   # 0 3 * * * bash -c 'source ~/.openclaw/shared/secrets/openclaw-secrets.env \\"
echo "   #   && openclaw agent --agent main \\"
echo "   #   --message \"Run the Total Recall Dream Cycle. Follow the instructions in \\"
echo "   # \$WORKSPACE/skills/total-recall/prompts/dream-cycle-prompt.md exactly. \\"
echo "   # Use READ_ONLY_MODE=false and DREAM_PHASE=1.\" \\"
echo "   #   --json >> \$WORKSPACE/logs/dream-cycle.log 2>&1'"
echo ""
echo "2. ADD SESSION RECOVERY to your agent's startup procedure:"
echo "   bash $SKILL_DIR/scripts/session-recovery.sh"
echo ""
echo "3. ADD TO YOUR AGENT'S CONTEXT (system prompt or MEMORY.md):"
echo "   'At session startup, read memory/observations.md for cross-session context.'"
echo ""
echo "4. (OPTIONAL) CONFIGURE memoryFlush pre-compaction hook:"
echo "   Run the observer in --flush mode before OpenClaw compacts context."
echo ""
echo "Logs:"
echo "  Observer:  tail -f $WORKSPACE/logs/observer.log"
echo "  Reflector: tail -f $WORKSPACE/logs/reflector.log"
if $_IS_MACOS && has_fswatch; then
  echo "  Watcher:   launchctl print gui/$(id -u)/com.total-recall.watcher"
elif has_inotify && has_systemd_user; then
  echo "  Watcher:   systemctl --user status total-recall-watcher"
fi
